name: CI/CD Pipeline for Floxify app

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        path: Agentra 

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 22.13.0  

    - name: Install dependencies
      working-directory: Agentra
      run: npm install

    - name: Deploy to EC2
      env:
        HOST: ${{ secrets.EC2_HOST }}
        USER: ${{ secrets.EC2_USER }}
        PRIVATE_KEY: ${{ secrets.EC2_KEY }}
      run: |
        # Save the private key to a file
        echo "$PRIVATE_KEY" > ssh_key
        chmod 600 ssh_key

        # Start SSH agent and add the private key
        eval $(ssh-agent -s)
        
        # Add the key to ssh-agent
        ssh-add ssh_key

        # Debugging: Use -v for verbose output
        ssh -v -o StrictHostKeyChecking=no -i ssh_key $USER@$HOST << 'EOF'
          cd /home/ubuntu/Agentra
          git pull origin main
          npm install --omit=dev

          # Ensure PM2 is using the environment variables
          pm2 restart Agentra || pm2 start npm --name "Agentra" -- start
        EOF

        # Clean up the private key
        rm -f ssh_key
